### ISSUE TITLE
关于GitHub不支持LaTex公式问题

### ISSUE THREAD

**Issue by DaisyLoveU** [fengdu78/Coursera-ML-AndrewNg-Notes#23]
如题，笔记的md文档的公式全部显示为$\ ***** $

**Comment by lartpang** [comment]
确实不支持，想看可以推荐给你个插件
[chrome web store](https://chrome.google.com/webstore/detail/github-with-mathjax/ioemnmodlmafdkllaclgeombjnmnbima?utm_source=chrome-ntp-icon)
[github](https://github.com/orsharir/github-mathjax)

不过也有些识别有问题，最直接的就是下载下来，本地拿markdown预览看

**Comment by DaisyLoveU** [comment]
非常感谢您的解答和解决方案！
