### ISSUE TITLE
第十二章SVM笔记中的几处错误

### ISSUE THREAD

**Issue by tanjuntao** [fengdu78/Coursera-ML-AndrewNg-Notes#30]
最近在学习SVM，把笔记V5.32中SVM这一章的内容通读了一遍，发现了下面几处小错误，希望作者有时间能够修复这些错误。

- `P174`：第二段，`我们同样可以看到，当z增大时，也就是相当于θTx增大时，z对应的值会变得非常小。`不是`z`的值变得非常小，而应该是`代价函数的值`变得非常小。

- `P178`：倒数第二段中，`反之，如果y = 0，我们观察一下，函数cost0(z)，它只有在z <= 1的区间里有函数值为0`。不是`z <= 1`，而应该是`z <= -1`。
- `P186`：第二段，`这个θTx(i) > = 1 或者θTx(i) < -1的，约束是可以被p(i).x >= 1这个约束所代替的`。不是`p(i).x >=1`而应该是`p(i).||θ||`。
- `P190`：第四段中，`得到hθ(x) = f1 + f2 + … + fn`，应该是`hθ(x) = (theta1)f1 + (theta2)f2 + ... + (thetan)fn`。

**Comment by fengdu78** [comment]
谢谢，我先看看

**Comment by fengdu78** [comment]
P179：倒数第二段中，反之，如果y = 0，我们观察一下，函数cost0(z)，它只有在z <= 1的区间里有函数值为0。不是z <= 1，而应该是z <= -1。
确实如此，修改了，这里是吴恩达老师讲课时候口误

**Comment by fengdu78** [comment]
P187：第二段，这个θTx(i) > = 1 或者θTx(i) < -1的，约束是可以被p(i).x >= 1这个约束所代替的。不是p(i).x >=1而应该是p(i).||θ||。
已经修改

**Comment by fengdu78** [comment]
P190：第四段中，得到hθ(x) = f1 + f2 + … + fn，应该是hθ(x) = (theta1)f1 + (theta2)f2 + ... + (thetan)fn。已经修改

**Comment by fengdu78** [comment]
都已经更新到新版本笔记

**Comment by tanjuntao** [comment]
> 都已经更新到新版本笔记

:thumbsup::thumbsup::thumbsup:
