### ISSUE TITLE
数学公式显示不正确

### ISSUE THREAD

**Issue by llearn** [fengdu78/Coursera-ML-AndrewNg-Notes#7]
Markdown 格式的文档，week1 里面 @fengdu78 
![qq 20180424091928](https://user-images.githubusercontent.com/3062671/39160954-d125d08e-47a0-11e8-9f76-f3b5927df911.png)

**Comment by Yeeler** [comment]
多謝作者共享，我原來也打算 写个笔记 方便日后回顾， 我也fork了这个repository。

@llearn 你需要下载一个markdown的Latex插件。 比如，我用Visual Studio Code 和 Markdown+Math

**Comment by GengboLiu** [comment]
https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima/related
